experimental:
  localPlugins:
    modsecurity:
      moduleName: "github.com/madebymode/traefik-modsecurity-plugin"
    geoblock:
      moduleName: "github.com/david-garcia-garcia/traefik-geoblock"
    sablier:
      moduleName: "github.com/sablierapp/sablier"
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
log:
  level: "TRACE"
providers:
  docker:
    exposedByDefault: false