experimental:
  localPlugins:
    modsecurity:
      moduleName: "github.com/david-garcia-garcia/traefik-modsecurity"
    geoblock:
      moduleName: "github.com/david-garcia-garcia/traefik-geoblock"
    sablier:
      moduleName: "github.com/sablierapp/sablier"
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
    realip:
      moduleName: "github.com/david-garcia-garcia/traefik-realip"
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
log:
  level: "TRACE"
api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false