entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
log:
  level: "TRACE"
api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false
# TLS configuration for testing self-signed certificates
tls:
  # Enable default certificate generation for unmatched domains
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
