## https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/

# Stage 1: Clone the repositories and checkout specific tags (builder stage)
FROM golang:1.24.3-alpine3.21 AS builder

# Install git in the builder container
RUN set -eux; \
    apk add --no-cache git

# Create the directory for the plugins
RUN set -eux; \
    mkdir -p /plugins-local/src/github.com/david-garcia-garcia && \
    mkdir -p /plugins-local/src/github.com/sablierapp && \
    mkdir -p /plugins-local/src/github.com/maxlerebourg

RUN set -eux && git clone https://github.com/david-garcia-garcia/traefik-modsecurity /plugins-local/src/github.com/david-garcia-garcia/traefik-modsecurity --branch v1.7.0 --single-branch
RUN set -eux && git clone https://github.com/sablierapp/sablier /plugins-local/src/github.com/sablierapp/sablier --branch v1.8.1 --single-branch
RUN set -eux && git clone https://github.com/david-garcia-garcia/crowdsec-bouncer-traefik-plugin /plugins-local/src/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin --branch 20250722b --single-branch
RUN set -eux && git clone https://github.com/david-garcia-garcia/traefik-geoblock /plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock --branch v1.1.2-beta.0 --single-branch

# Stage 2: Copy the plugins
FROM traefik:3.1.7

# To make sure that if database location changes, the plugin will still works
ENV TRAEFIK_PLUGIN_GEOBLOCK_PATH=/plugins-local/src/github.com/david-garcia-garcia/traefik-geoblock

# Copy the plugins from the builder stage
COPY --from=builder /plugins-local /plugins-local