## https://traefik.io/blog/using-private-plugins-in-traefik-proxy-2-5/

# Stage 1: Clone the repositories and checkout specific tags (builder stage)
FROM golang:1.19-alpine AS builder

# Install git in the builder container
RUN set -eux; \
    apk add --no-cache git

# Create the directory for the plugins
RUN set -eux; \
    mkdir -p /plugins-local/src/github.com/acouvreur && \
    mkdir -p /plugins-local/src/github.com/jcchavezs && \
    mkdir -p /plugins-local/src/github.com/nscuro && \
    mkdir -p /plugins-local/src/github.com/sablierapp

RUN set -eux && git clone https://github.com/acouvreur/traefik-modsecurity-plugin /plugins-local/src/github.com/acouvreur/traefik-modsecurity-plugin --branch v1.3.0 --single-branch
RUN set -eux && git clone https://github.com/jcchavezs/coraza-http-wasm-traefik /plugins-local/src/github.com/jcchavezs/coraza-http-wasm-traefik --branch v0.3.0 --single-branch
RUN set -eux && git clone https://github.com/nscuro/traefik-plugin-geoblock /plugins-local/src/github.com/nscuro/traefik-plugin-geoblock --branch v0.14.0 --single-branch
RUN set -eux && git clone https://github.com/sablierapp/sablier /plugins-local/src/github.com/sablierapp/sablier --branch v1.8.1 --single-branch

# Stage 2: Copy the plugins
FROM traefik:3.1.7

# Copy the plugins from the builder stage
COPY --from=builder /plugins-local /plugins-local